config/routes.rb
Rails.application.routes.draw do
	resources :outreaches do
	  resources :messages do
		  resources :templates
	  end
	end
	
	#naked routes 
	resources :messages
	resources :templates

	# API

	namespace :api do
		resources :outreaches do
			resources :messages do
				resources :templates
			end
		end
		resources :messages
		resources :templates

	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/outreach.rb
class Outreach < ApplicationRecord
	
end

app/controllers/api/outreaches_controller.rb
module Api

  class OutreachesController < ApiController
    before_action :set_outreach, only: [:show, :edit, :update, :destroy]

    # GET /outreaches
    # GET /outreaches.json
    def index
      @outreaches = Outreach.all
      render json: @outreaches
    end

    # GET /outreaches/1
    # GET /outreaches/1.json
    def show
      render json: @outreach
    end

    # GET /outreaches/new
    def new
      @outreach = Outreach.new
      render json: @outreach
    end

    # GET /outreaches/1/edit
    def edit
    end

    # POST /outreaches
    # POST /outreaches.json
    def create
      @outreach = Outreach.new(outreach_params)
      if @outreach.save
        render json: @outreach
      else
        format.json { render json: @outreach.errors, status: :unprocessable_entity }
      end
    end

    # PATCH/PUT /outreaches/1
    # PATCH/PUT /outreaches/1.json
    def update
      if @outreach.update(outreach_params)
        render json: @outreach
      else
        format.json { render json: @outreach.errors, status: :unprocessable_entity }
      end
    end

    # DELETE /outreaches/1
    # DELETE /outreaches/1.json
    def destroy
      @outreach.destroy
      format.json { head :no_content }
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_outreach
        @outreach = Outreach.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def outreach_params
        params.require(:outreach).permit(:name, :message)
      end
  end
end

app/controllers/outreaches_controller.rb
class OutreachesController < ApplicationController
  before_action :set_outreach, only: [:show, :edit, :update, :destroy]
  before_action :prepare_messages
  # GET /outreaches
  # GET /outreaches.json
  def index
    @outreaches = Outreach.all
  end

  # GET /outreaches/1
  # GET /outreaches/1.json
  def show
  end

  # GET /outreaches/new
  def new
    @outreach = Outreach.new
  end

  # GET /outreaches/1/edit
  def edit
  end

  # POST /outreaches
  # POST /outreaches.json
  def create
    @outreach = Outreach.new(outreach_params)

    respond_to do |format|
      if @outreach.save
        format.html { redirect_to @outreach, notice: 'Outreach was successfully created.' }
        format.json { render :show, status: :created, location: @outreach }
      else
        format.html { render :new }
        format.json { render json: @outreach.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /outreaches/1
  # PATCH/PUT /outreaches/1.json
  def update
    respond_to do |format|
      puts "PARAMS: #{outreach_params}"

      if @outreach.update(outreach_params)
        format.html { redirect_to @outreach, notice: 'Outreach was successfully updated.' }
        format.json { render :show, status: :ok, location: @outreach }
      else
        format.html { render :edit }
        format.json { render json: @outreach.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /outreaches/1
  # DELETE /outreaches/1.json
  def destroy
    @outreach.destroy
    respond_to do |format|
      format.html { redirect_to outreaches_url, notice: 'Outreach was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_outreach
      @outreach = Outreach.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def outreach_params
      params.require(:outreach).permit(:name, :message_id)
    end

    def prepare_messages
      @messages = Message.all
    end

end

app/views/outreaches/_form.html.erb
<%= form_with(model: outreach, local: true) do |form| %>
  <% if outreach.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(outreach.errors.count, "error") %> prohibited this outreach from being saved:</h2>

      <ul>
      <% outreach.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <div class="ui input">
      <%= form.text_field :name %>
    </div>
  </div>

  <div class="field">
    <%= form.label :message %><br />
    <%= react_component 'Message/MessageComponent', selected: @outreach.message_id %>
  </div>
  <br/> 
  

  <div >
    <%= form.submit class: "actions ui primary button" %>
  </div>

<% end %>

app/views/outreaches/edit.html.erb
<h1>Editing Outreach</h1>

<%= render 'form', outreach: @outreach %>

<%= link_to 'Show', @outreach %> |
<%= link_to 'Back', outreaches_path %>

app/views/outreaches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Outreaches</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @outreaches.each do |outreach| %>
      <tr>
        <td><%= outreach.name %></td>
        <td><%= outreach.message_id %></td>
        <td><%= link_to 'Show', outreach %></td>
        <td><%= link_to 'Edit', edit_outreach_path(outreach) %></td>
        <td><%= link_to 'Destroy', outreach, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Outreach', new_outreach_path %>

app/views/outreaches/new.html.erb
<h1>New Outreach</h1>

<%= render 'form', outreach: @outreach %>

<%= link_to 'Back', outreaches_path %>

app/views/outreaches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @outreach.name %>
</p>

<p>
  <strong>Message:</strong>
  <%= @outreach.message_id %>
</p>

<%= link_to 'Edit', edit_outreach_path(@outreach) %> |
<%= link_to 'Back', outreaches_path %>